// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibmojkhyyfizianmooez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibW9qa2h5eWZpemlhbm1vb2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2ODk5NDQsImV4cCI6MjA4NTI2NTk0NH0.b0OcE_PJWj9Aj0IkwvMyncdp8KOCOcW_xiCV7PIUpXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});